// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// get_bits
std::vector< int > get_bits(unsigned long x);
RcppExport SEXP Lab6_get_bits(SEXP xSEXP) {
BEGIN_RCPP
    SEXP __sexp_result;
    {
        Rcpp::RNGScope __rngScope;
        Rcpp::traits::input_parameter< unsigned long >::type x(xSEXP );
        std::vector< int > __result = get_bits(x);
        PROTECT(__sexp_result = Rcpp::wrap(__result));
    }
    UNPROTECT(1);
    return __sexp_result;
END_RCPP
}
// brute_force_knapsack_C
List brute_force_knapsack_C(NumericMatrix x, int W);
RcppExport SEXP Lab6_brute_force_knapsack_C(SEXP xSEXP, SEXP WSEXP) {
BEGIN_RCPP
    SEXP __sexp_result;
    {
        Rcpp::RNGScope __rngScope;
        Rcpp::traits::input_parameter< NumericMatrix >::type x(xSEXP );
        Rcpp::traits::input_parameter< int >::type W(WSEXP );
        List __result = brute_force_knapsack_C(x, W);
        PROTECT(__sexp_result = Rcpp::wrap(__result));
    }
    UNPROTECT(1);
    return __sexp_result;
END_RCPP
}
