# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

get_bits <- function(x) {
    .Call('Lab6_get_bits', PACKAGE = 'Lab6', x)
}

bf_cpp <- function(x, W) {
    .Call('Lab6_bf_cpp', PACKAGE = 'Lab6', x, W)
}

